### ISSUE TITLE
Success and Error message without response

### ISSUE THREAD

**Issue by GergelyLakatos** [abarta/vue2-multi-uploader#12]
Hi!

I really like your component, however I found a little problem. If I want to write out that upload was successfull or not, I can not write just text. I got this `[object Object].Upload Success!` beacuse [in your code](https://github.com/abarta/vue2-multi-uploader/blob/4682b647aba083d1361d861729a4de368b38f0b0/src/MultipleFileUploader.vue#L230) you append the respond & error with the text.
My suggestion that it should be separated.

Greg

**Comment by abarta** [comment]
Hi there,

I understand what you are suggesting, however I do not agree with it. When interacting with a server one  expects a response from it. But you are free to fork it and change the code as you desire.

Thanks!
