### ISSUE TITLE
REQUEST: Http Method type

### ISSUE THREAD

**Issue by abishekrsrikaanth** [abarta/vue2-multi-uploader#2]
Can you provide support for both Http `POST` and Http `PUT` requests based on the props defined? Could be something like

```
<multiple-file-uploader 
           action="http://.." 
           method="POST" 
           onSuccess="" 
          onError=""></multiple-file-uploader>
```

Additionally, it would be great to have `postData` to add any additional metadata to the request.

**Comment by abarta** [comment]
Hi there,

Thanks for the suggestions, both were added as optional props.
