### ISSUE TITLE
Adding to a component project Laravel y Vuejs 2

### ISSUE THREAD

**Issue by asarmiento** [abarta/vue2-multi-uploader#3]
Hi, I'm trying to add the library to a component I have in my project. But I have not been able to make it work out these mistakes, I am new to Vue.js.

Here I put the code as I have in my project

I am working on laravel 5.4 and the whole view with components of vue

in bootstrap.js
`Vue.use(require('vue2-multi-uploader'));`

in CreateCheck.vue

``` 
<multiple-file-uploader
postURL="http://softadventist.dev/tesoreria/save-check"
 :minItems="1" :maxItems="10"></multiple-file-uploader >
```

` import MultipleFileUploader from 'vue2-multi-uploader'
    export default {
        props: ['title','url','banks'],
        components: {vSelect, MultipleFileUploader},`

El problema que tengo es que espero en el conntrollador items y me sale en blanco lo recibo como file o como string he igual no me llega el archivo.
The problem I have is that I wait in the conntrollator items and it goes blank I receive it as a file or as a string. I do not get the file.

**Comment by abarta** [comment]
Hi there, 

Could you be more specific?  You say "I receive it as a file or as a string. I do not get the file." Are you sure you are using it correctly? Do you see the drop area like in the demo?

**Comment by abarta** [comment]
Closed for inactivity.

**Comment by asarmiento** [comment]
Sorry I could not see this topic again.


Look in the controller of the post path where the file should be received so I have it.

```
 public function postUpload()
    {
        echo json_encode(Input::all());
        die;
    }
```

This is what i get: 

```
{items: [{}]}
items:[{}]
0:{}
```

If I put it like that:
```
 public function postUpload()
    {
        echo json_encode(Input::file('items'));
        die;
    }
```

I get this:

```
[{}]
0:{}
```
If I put it like that:
```
    public function postUpload(Request $request)
    {
        echo json_encode($request->allFiles());
        die;
    }
```
I get this:
```
{items: [{}, {}, {}]}
items:[{}, {}, {}]
0:{}
1:{}
2:{}
```
Sorry, I only speak spanish and I'm using google translate
