### ISSUE TITLE
Aplicando en Laravel

### ISSUE THREAD

**Issue by asarmiento** [abarta/vue2-multi-uploader#4]
Sorry I could not see this topic again.

Look in the controller of the post path where the file should be received so I have it.

```
 public function postUpload()
    {
        echo json_encode(Input::all());
        die;
    }
```

This is what i get: 

```
{items: [{}]}
items:[{}]
0:{}
```

If I put it like that:
```
 public function postUpload()
    {
        echo json_encode(Input::file('items'));
        die;
    }
```

I get this:

```
[{}]
0:{}
```
If I put it like that:
```
    public function postUpload(Request $request)
    {
        echo json_encode($request->allFiles());
        die;
    }
```
I get this:
```
{items: [{}, {}, {}]}
items:[{}, {}, {}]
0:{}
1:{}
2:{}
```
Sorry, I only speak spanish and I'm using google translate

**Comment by abarta** [comment]
Hi there,

I think you are not initializing the component properly. I've uploaded the two demo files for you to have a look at:
https://github.com/abarta/vue2-multi-uploader/blob/master/demo/App.vue
https://github.com/abarta/vue2-multi-uploader/blob/master/demo/main.js

Please try to include the uploader this way. Also, as you mentioned Laravel, are you including the CSRF token? Here's the documentation:
https://laravel.com/docs/5.4/csrf

Let me know if I can help any further.

Thanks!

**Comment by asarmiento** [comment]
Subi los archivos a un repositorio para que los puedas ver como lo tengo implementado los js 
(I upload the files to a repository so you can see how I have implemented the js)

[https://github.com/asarmiento/tempUploadFile/blob/master/resources/assets/js/components/Example.vue](url)
[https://github.com/asarmiento/tempUploadFile/blob/master/resources/assets/js/app.js](url)

Aqui te muestro como lo tengo en php (
Here I show you how I have it in php)

[https://github.com/asarmiento/tempUploadFile/blob/master/resources/views/home.blade.php](url)
[https://github.com/asarmiento/tempUploadFile/blob/master/routes/web.php](url)
[https://github.com/asarmiento/tempUploadFile/blob/master/app/Http/Controllers/HomeController.php](url)

**Comment by asarmiento** [comment]
Listo Solucionado. gracias

**Comment by abarta** [comment]
Glad to hear it works now.

Have a good day in Costa Rica!
