### ISSUE TITLE
This is potential feature

### ISSUE THREAD

**Issue by opii** [abarta/vue2-multi-uploader#5]
Hello, i really like your plugin, but i would like to implement something similar with one additional feature, after we add files first, to have ability to remove one by one and to add files later, after first addition.
Do you have a plan to add those features? 
I would be glad to help!

**Comment by abarta** [comment]
Hi opii,

Thanks for using the component.

Do you mean also having the option to remove each individual file in the list before uploading the batch?
Currently you can remove all and add again a different selection of files.

**Comment by opii** [comment]
Hello Abarta, 
yes, that is one feature i think it will be usable.
Another one is to, after first file addition, to have ability to add more, currently we can select only files from one folder.

**Comment by abarta** [comment]
I understand. Unfortunately, I am not developing new features at this time. But, as it is open source, you are free to fork it and make the changes you want and submit a pull request. Thanks!
