### ISSUE TITLE
Enhancement Proposal

### ISSUE THREAD

**Issue by Mushood** [abarta/vue2-multi-uploader#7]
Hello Abarta

I really like your plugin and would like to contribute.

Here is what I would like to work on:

Ability to change the texts in the layout

Right now, we have 3 texts which are hard-coded:

Add files
Drop multiple files here.
Space for your instructions
I would like to add them as props, which can be configurable, if needed. The defaults would remain the same.

If this sounds like a good idea, I would do the same for the div with class="uploadBoxMain"

Let me know what you think

**Comment by abarta** [comment]
Hi Mushood,

Thanks for using it. I'm glad you like it. Yes it sounds nice to have the text messages as props, so they can be translated or changed. You can also remove the div that holds the text "Space for your instructions". Just don't change variable names. Do a PR when done and I will review it and merge if good. 

Andrei

**Comment by Mushood** [comment]
Hello

I sent you a PR for the aforementioned proposal.

I would like to add the following enhancements in the future:
1. Ability to add files one by one
2. Ability to remove files one by one
3. Add a hover class  when files are being dropped

Let me know if those are changes you'd be interested in

**Comment by abarta** [comment]
Hi Mushood,

Thanks for the PR, seems fine, I will look at it in detail next week and merge it if the are no issues. 

Yes, what you are describing is useful extra functionality, both adding bulk and one by one. The hover class I don't understand but as it is a css class, that can be easily modifying by people using it.

Please for next PR, also update the README.md file so others know what you have added/changed.

Have a nice weekend!

Andrei

**Comment by Mushood** [comment]
Hello Abarta,

By the hover class, I meant that when people are dropping their files, they have a visual confirmation that the files can be dropped here.

As for the README.md, understood. Just confirm to me the naming convention and I will do the necessary for the README.md

Have a nice weekend too!

**Comment by abarta** [comment]
Thanks for clearing that up.

Yes, both naming convention and hover class are fine. Then I will wait for the updated PR with the README file. You can put all new prop in that table, all of them are strings and have default values. 

Best,
Andrei

**Comment by Mushood** [comment]
Hello Abarta

I updated the README file. Do check it and let me know if any changes need to be done.

Have a good week ahead

**Comment by abarta** [comment]
Tested, all good, pushed to npm, just removed the header prop which was not used anymore. Thanks a lot, looking forward to next PR.

**Comment by abarta** [comment]
A good week to you as well in Mauritius! Wish I had the same weather here.

**Comment by abarta** [comment]
Good week to you too in sunny Mauritius!

**Comment by Mushood** [comment]
Sorry Abarta, was quite busy late week and things are looking busy this week as well. I'll be working on the project next week ;)

Its too hot in Mauritius right now! :P

**Comment by abarta** [comment]
Take your time to develop and test. Have a good busy week.

**Comment by abarta** [comment]
Closing this thread, if you do the PR, please open new one.

Happy Holidays!
