### ISSUE TITLE
Some changes

### ISSUE THREAD

**Issue by SergioReis97** [abarta/vue2-multi-uploader#9]
Not really an issue, just gonna leave this here.
Did some small changes that I required, if this seems interesting to you I can do a PR.
https://github.com/SergioReis97/vue2-multi-uploader/commit/29ec535e073d4e9be8c5466be4d2a7397c8c5aca
Cheers

**Comment by abarta** [comment]
Bom dia Sergio,

Thanks for writing and using the component.
I see you added a post header to the axios request, I guess it would be useful for some.

You're repo copy also has node_modules and another folder that I cannot merge, please only change the .vue file and I will recompile both the dist and demo folders.

To test out your version in the demo, modify webpack.config.js lines from:
```
  entry: './src/index.js',
  output: {
    path: path.resolve(__dirname, './dist'),
    publicPath: '/dist/',
    filename: 'build.js',

```
to:

```
  entry: './demo/main.js',
  output: {
    path: path.resolve(__dirname, './demo'),
    publicPath: '/demo/',
    filename: 'demo.js',
```
and run 
`npm run build`

Now your demo should show your changes.

**Comment by SergioReis97** [comment]
Ahhh yes, my bad, didn't notice there was no .gitignore and just ran `git add .` :sweat_smile: 
I did some more changes since it was some stuff i required, Including adding class to dropArea on drag events for when dragging files to upload to have some feedback. And the postMeta option didn't really work in my case since i required some couple parameters and just one wasn't cutting it. the postData i have is an object variable that converts each key => value to the formdata.
for example, 
`var objectoTeste = {test1:"aaa",test2:"bbb",test3:"ccc"}`
Cheers!

**Comment by abarta** [comment]
Ok, please do another PR with just the modified .vue file and readme and I will approve it.
Thanks!

**Comment by abarta** [comment]
merged, thanks!
